// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_peivyYi7nA-V5ebsknTkUaA9yjjeUH0',
    appId: '1:414280440193:web:da1df81335995a9eec7080',
    messagingSenderId: '414280440193',
    projectId: 'evently-app-fec86',
    authDomain: 'evently-app-fec86.firebaseapp.com',
    storageBucket: 'evently-app-fec86.firebasestorage.app',
    measurementId: 'G-1HDFQZ7716',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtE4JNh_6LHLY2p4SCEft_jzKiQ8vwnok',
    appId: '1:414280440193:android:84ac69603575f25aec7080',
    messagingSenderId: '414280440193',
    projectId: 'evently-app-fec86',
    storageBucket: 'evently-app-fec86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hJunJZS3QvDuX4RCMVBJfJlhMJnDVhw',
    appId: '1:414280440193:ios:532915d6570c372bec7080',
    messagingSenderId: '414280440193',
    projectId: 'evently-app-fec86',
    storageBucket: 'evently-app-fec86.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6hJunJZS3QvDuX4RCMVBJfJlhMJnDVhw',
    appId: '1:414280440193:ios:532915d6570c372bec7080',
    messagingSenderId: '414280440193',
    projectId: 'evently-app-fec86',
    storageBucket: 'evently-app-fec86.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_peivyYi7nA-V5ebsknTkUaA9yjjeUH0',
    appId: '1:414280440193:web:11c0e10b23c007feec7080',
    messagingSenderId: '414280440193',
    projectId: 'evently-app-fec86',
    authDomain: 'evently-app-fec86.firebaseapp.com',
    storageBucket: 'evently-app-fec86.firebasestorage.app',
    measurementId: 'G-CF37V4E9CR',
  );
}
